# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SignIn' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SignIn

  pod 'Firebase/Analytics'
  pod 'GoogleSignIn'
  pod 'Firebase/Auth'
  pod 'flex-api-ios-sdk'
  
  target 'SignInTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SignInUITests' do
    # Pods for testing
  end

end
